packages:
  - packages/*
  - app/main
  - app/windows/*/*
  - tooling/*
  - templates/**/*

catalogs:
  dev:
    "@tailwindcss/vite": ^4.1.13
    "@vitejs/plugin-react": ^5.0.3
    '@pixpilot/dev-config': ^3.1.2
    '@testing-library/jest-dom': ^6.8.0
    '@testing-library/react': ^16.3.0
    '@testing-library/user-event': ^14.6.1
    '@types/node': ^24.5.2
    '@types/react': ^19.1.13
    '@types/react-dom': ^19.1.9
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    electron-vite-toolkit: ^0.5.0
    electron: 38.0.0
    eslint: ^9.35.0
    jsdom: ^26.1.0
    prettier-plugin-tailwindcss: ^0.6.14
    prettier: ^3.6.2
    typescript-eslint: ^8.44.0
    typescript: ^5.9.2
    vite: ^7.1.6
    vitest: ^3.2.4
  prod:
    react-icons: ^5.5.0
    react: ^19.1.1
    react-dom: ^19.1.1
