packages:
  - packages/*
  - app/main
  - app/windows/*/*
  - tooling/*

catalogs:
  dev:
    "@tailwindcss/vite": ^4.1.12
    "@vitejs/plugin-react": ^5.0.0
    '@pixpilot/dev-config': ^3.1.2
    '@testing-library/jest-dom': ^6.6.3
    '@testing-library/react': ^16.1.0
    '@testing-library/user-event': ^14.5.2
    '@types/node': ^24.2.1
    '@types/react': ^19.1.11
    '@types/react-dom': ^19.1.7
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    electron: 38.0.0
    eslint: ^9.34.0
    jsdom: ^26.0.0
    prettier-plugin-tailwindcss: ^0.6.14
    prettier: ^3.6.2
    rimraf: ^5.0.5
    tailwindcss: 4.1.12
    typescript-eslint: ^8.40.0
    typescript: ^5.9.2
    vite: ^7.1.4
    vitest: ^3.2.4
  prod:
    react-icons: ^5.5.0
    react: ^19.1.1
    react-dom: ^19.1.1
