# This file serves as the main CI entry point for the React Electron template.

name: React Electron Template CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - .editorconfig
      - '.vscode/**'

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  run-ci:
    name: CI - React Template
    uses: ./.github/workflows/ci.yml
    with:
      distribution-channel: main
    permissions:
      contents: write
      id-token: write
      attestations: write

  dependabot:
    permissions:
      contents: write
      pull-requests: write
    needs:
      - run-ci
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
